repo_url: https://github.com/flanksource/docs/
repo_name: Flanksource Mission Control
site_name: Flanksource Mission Control
extra:
  generator: false
extra_css:
  - style.css
theme:
  logo: ./images/flanksource-icon-white.svg
  favicon: ./images/flanksource-icon.png
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: light-blue
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: light-blue
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
  features:
    - content.tabs.link
    - search.suggest
    - search.highlight
    - header.autohide
    # - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    # - toc.integrate
    # - navigation.tracking
    # - navigation.expand
    # - navigation.top
markdown_extensions:
  - admonition
  - fenced_code
  - def_list
  - pymdownx.smartsymbols
  - toc:
      permalink: False
      anchorlink: True
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - codehilite:
      linenums: true
nav:
  - Home: ./index.md
  - Configuration:
      - Installation: ./config-db/tutorials/install-helm.md
      - Getting Started:
          - Overview: ./config-db/overview.md
          - Quick Start: ./config-db/tutorials/example-git-file.md
      - Concepts:
          - Configuration: ./config-db/tutorials/configuration.md
          - Secret Management: ./config-db/concepts/secret-management.md
          - Extraction: ./config-db/concepts/extraction.md
          - Templating: ./config-db/concepts/templating.md
          - Maping custom creation/deletion time: ./config-db/concepts/custom-creation-deletion-time.md
          - Transform: ./config-db/concepts/transform.md
          - Mask: ./config-db/concepts/mask.md
          - Exclude: ./config-db/concepts/exclude.md
      - Scrapers:
          - AWS: ./config-db/scrapers/aws.md
          - Azure DevOps: ./config-db/scrapers/azure-devops.md
          - Files (Local/HTTP/Git): ./config-db/scrapers/file.md
          - Files (Kubernetes): ./config-db/scrapers/kubernetes-file.md
          - Kubernetes: ./config-db/scrapers/kubernetes.md
          - SQL: ./config-db/scrapers/sql.md
          - Custom: ./config-db/scrapers/custom.md
      - Local Development:
          - Installation: ./config-db/tutorials/install-standalone.md
          - CLI: ./config-db/tutorials/cli.md

  - Health Checks:
      - Overview: ./canary-checker/overview.md
      - Getting Started: ./canary-checker/tutorials/getting-started.md
      - Concepts:
          - Secret Management: ./canary-checker/concepts/secret-management.md
          - Templating: ./canary-checker/concepts/templating.md
      - Local Development:
          - CLI: ./canary-checker/tutorials/run.md
      - References:
          - CanarySpec: ./canary-checker/reference/canary-spec.md
          - AlertManager: ./canary-checker/reference/alert-manager.md
          - CloudWatch: ./canary-checker/reference/cloudwatch.md
          - ConfigDB: ./canary-checker/reference/configdb.md
          - ContainerdPull: ./canary-checker/reference/containerd-pull.md
          - ContainerdPush: ./canary-checker/reference/containerd-push.md
          - DNS: ./canary-checker/reference/dns.md
          - DockerPull: ./canary-checker/reference/docker-pull.md
          - DockerPush: ./canary-checker/reference/docker-push.md
          - EC2: ./canary-checker/reference/ec2.md
          - Elasticsearch: ./canary-checker/reference/elasticsearch.md
          - Exec: ./canary-checker/reference/exec.md
          - GCS Bucket: ./canary-checker/reference/gcs-bucket.md
          - GCS Database Backup: ./canary-checker/reference/gcs-database-backup.md
          - GitHub: ./canary-checker/reference/github.md
          - Helm: ./canary-checker/reference/helm.md
          - HTTP: ./canary-checker/reference/http.md
          - ICMP: ./canary-checker/reference/icmp.md
          - JMeter: ./canary-checker/reference/jmeter.md
          - JUnit: ./canary-checker/reference/junit.md
          - Kubernetes: ./canary-checker/reference/kubernetes.md
          - LDAP: ./canary-checker/reference/ldap.md
          - Mongo: ./canary-checker/reference/mongo.md
          - MS SQL Server: ./canary-checker/reference/mssql.md
          - MySQL: ./canary-checker/reference/mysql.md
          - Namespace: ./canary-checker/reference/namespace.md
          - Pod: ./canary-checker/reference/pod.md
          - Postgres: ./canary-checker/reference/postgres.md
          - Prometheus: ./canary-checker/reference/prometheus.md
          - Redis: ./canary-checker/reference/redis.md
          - Restic: ./canary-checker/reference/restic.md
          - S3 Bucket: ./canary-checker/reference/s3-bucket.md
          - S3: ./canary-checker/reference/s3.md
          - SFTP: ./canary-checker/reference/sftp.md
          - SMB / CIFS: ./canary-checker/reference/smb.md
          - TCP: ./canary-checker/reference/tcp.md

  - Logging:
      - Overview: ./apm-hub/overview.md
      - Quick Start: ./apm-hub/quick-start.md
      - Concepts:
          - Configuration: ./apm-hub/concepts/configuration.md
          - Authentication: ./apm-hub/concepts/authentication.md
          - API: ./apm-hub/concepts/api.md
          - Routing: ./apm-hub/concepts/routing.md
          - Templating: ./apm-hub/concepts/templating.md
      - Backends:
          - File: ./apm-hub/backends/file.md
          - Kubernetes: ./apm-hub/backends/kubernetes.md
          - Elasticsearch: ./apm-hub/backends/elasticsearch.md
          - OpenSearch: ./apm-hub/backends/opensearch.md
      - Local Development:
          - Installation: ./apm-hub/tutorials/install.md
          - CLI: ./apm-hub/tutorials/cli.md

  - Topology:
      - Overview: ./topology/overview.md
      - Concepts:
          - Topology: ./topology/concepts/topology.md
          - Components: ./topology/concepts/components.md
          - Configs: ./topology/concepts/configs.md
          - Properties: ./topology/concepts/properties.md
          - Health Checks: ./topology/concepts/health-checks.md
          - Secret Management: ./topology/concepts/secret-management.md
          - Templating: ./topology/concepts/templating.md
      - Examples:
          Kubernetes: ./topology/examples/kubernetes.md
          Kubernetes (Workload): ./topology/examples/kubernetes-workload.md
          From Configuration: ./topology-configuration.md
