repo_url: https://github.com/flanksource/docs/
repo_name: Flanksource Docs
site_name: Flanksource Docs
theme:
  logo: ./images/flanksource-white.svg
  favicon: ./images/flanksource-icon.png
  name: material
  palette:
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: indigo
    accent: light-blue
    toggle:
      icon: material/lightbulb
      name: Switch to light mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: indigo
    accent: light-blue
    toggle:
      icon: material/lightbulb-outline
      name: Switch to dark mode
  features:
    - content.tabs.link
    - search.suggest
    - search.highlight
    # - navigation.instant
    # - navigation.sections
    # - navigation.tracking
    # - navigation.expand
    # - navigation.top
markdown_extensions:
  - admonition
  - fenced_code
  - pymdownx.smartsymbols
  - toc:
      toc_depth : "1-1"
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.tabbed
  - codehilite:
      linenums: true
nav:
  - Home:  ./index.md
  - Installation: ./installation.md
  - Configuration:
    - Install CLI: ./config-db/tutorials/install-cli.md
    - Getting Started: ./config-db/tutorials/getting-started-configdb.md
    - Deploy to Kubernetes: ./config-db/tutorials/install-kubernetes.md
  - Health Checks:
    - Overview: ./canary-checker/overview.md
    - Getting Started: ./canary-checker/tutorials/getting-started.md
    - Contributing: ./canary-checker/tutorials/dev-guide.md
    - Install CLI: ./canary-checker/tutorials/run.md
    - Install on Standalone Server: ./canary-checker/tutorials/server.md
    - Install Kubernetes Operator: ./canary-checker/tutorials/operator.md
  - Concepts:
    - Secret Management: ./concepts/secret-management.md
    - Templating: ./concepts/templating.md
  - Reference:
    - Glossary: ./reference/glossary.md
    - Canary-checker:
      - Checks:
        - Cloudwatch: ./reference/canary-checker/checks/cloudwatch.md
        - ConfigDB: ./reference/canary-checker/checks/configdb.md
        - Containerd Pull: ./reference/canary-checker/checks/containerd-pull.md
        - Containerd Push: ./reference/canary-checker/checks/containerd-push.md
        - DNS: ./reference/canary-checker/checks/dns.md
        - Docker Pull: ./reference/canary-checker/checks/docker-pull.md
        - Docker Push: ./reference/canary-checker/checks/docker-push.md
        - EC2: ./reference/canary-checker/checks/ec2.md
        - Elasticsearch: ./reference/canary-checker/checks/elasticsearch.md
        - Exec: ./reference/canary-checker/checks/exec.md
        - GCSBucket: ./referencecanary-checker/checks/gcs-bucket.md
        - GCS Database Backup: ./reference/canary-checker/checks/gcs-database-backup.md
        - Helm: ./reference/canary-checker/checks/helm.md
        - HTTP: ./reference/canary-checker/checks/http.md
        - ICMP: ./reference/canary-checker/checks/icmp.md
        - JMeter: ./reference/canary-checker/checks/jmeter.md
        - JUnit: ./reference/canary-checker/checks/junit.md
        - Kubernetes: ./reference/canary-checker/checks/kubernetes.md
        - LDAP: ./reference/canary-checker/checks/ldap.md
        - Mongo: ./reference/canary-checker/checks/mongo.md
        - MsSql: ./reference/canary-checker/checks/mssql.md
        - MySQL: ./reference/canary-checker/checks/mysql.md
        - Namespace: ./reference/canary-checker/checks/namespace.md
        - Pod: ./reference/canary-checker/checks/pod.md
        - Postgres: ./reference/canary-checker/checks/postgres.md
        - Prometheus: ./reference/canary-checker/checks/prometheus.md
        - Redis: ./reference/canary-checker/checks/redis.md
        - Restic: ./reference/canary-checker/checks/restic.md
        - S3 Bucket: ./reference/canary-checker/checks/s3-bucket.md
        - S3: ./reference/canary-checker/checks/s3.md
        - SFTP: ./reference/canary-checker/checks/sftp.md
        - SMB / CIFS: ./reference/canary-checker/checks/smb.md
    - Config-db:
      - Config Types:
        - AWS: ./reference/config-db/config-types/aws.md
        - File: ./reference/config-db/config-types/file.md
        - Kubernetes: ./reference/config-db/config-types/kubernetes.md
        - KubernetesFile: ./reference/config-db/config-types/kubernetes-file.md
    - Topology:
      - Common:
        - Kubernetes Cluster: ./topology/common/kubernetes-cluster.md