apiVersion: canaries.flanksource.com/v1
kind: Canary
metadata:
  name: http-pass
spec:
  interval: 30
  http:
    - endpoint: https://httpstat.us/200
      thresholdMillis: 3000
      responseCodes: [201, 200, 301]
      responseContent: ""
      maxSSLExpiry: 7
      name: "httpstat healthy"
---
apiVersion: canaries.flanksource.com/v1
kind: Canary
metadata:
  name: dns-present
spec:
  interval: 30
  dns:
    - server: 8.8.8.8
      name: "DNS healthly"
      port: 53
      query: "flanksource.com"
      querytype: "A"
      minrecords: 1
      exactreply: ["99.83.190.102", "75.2.70.75"]
      timeout: 10
